# Generated by Django 4.2.3 on 2023-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
