# Generated by Django 4.2.3 on 2023-07-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_department_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='employees.employee'),
        ),
    ]
