# Generated by Django 4.2.3 on 2023-07-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_department_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='years_of_experience',
        ),
    ]
