# Generated by Django 4.2.3 on 2023-07-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
