# Generated by Django 4.2.3 on 2023-07-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_manager_id_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
