# Generated by Django 4.2.3 on 2023-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_department_promotion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='promotion_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
